version: "3.8"
name: "educate_me"
services:
 db:
  image: mysql:latest
  platform: linux/amd64
  restart: always
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: educate_me_db
  command: --default-authentication-plugin=mysql_native_password
  volumes:
   - ./mysql-data:/var/lib/mysql

 phpmyadmin:
  image: phpmyadmin:latest
  platform: linux/amd64
  ports:
   - "8080:80"
  depends_on:
   - db
